### PR TITLE
add function and alias snippets to language-shellscript

### PR DESCRIPTION
**Pull request by ecollis6**
#41 - Add alias and function to snippets

### CODE REVIEW

**Comment by 50Wliu** [comment]
Please alphabetize these and use ellipses (`…`) instead of triple dots (`...`) to stay consistent with the other snippets.

**Comment by ecollis6** [comment]
@50Wliu I made this change and committed my code.

**Comment by 50Wliu** [comment]
Thanks!

**Comment by Ben3eeE** [comment]
@50Wliu did this close https://github.com/atom/language-shellscript/issues/41?

**Pull request merged**
