### PR TITLE
Correctly parse prompts with brackets

### PR DESCRIPTION
**Pull request by elyscape**
### Description of the Change

This pull request fixes the pattern that is supposed to parse the shell prompt when it is surrounded by brackets. Some distros, notably those based on Fedora or RHEL, default to prompts of the form `[user@host cwd]$ `. Unfortunately, the pattern to match these currently assumes that there are one or more characters after the closing bracket and before the prompt separator. To illustrate:
```shellsession
[root@04baf0b50a63 /]# # Fedora default
[root@04baf0b50a63 /]# echo "$PS1"
[\u@\h \W]\$
[root@04baf0b50a63 /]# ls
bin   dev  home  lib64       media  opt   root  sbin  sys  usr
boot  etc  lib   lost+found  mnt    proc  run   srv   tmp  var
[root@04baf0b50a63 /]# # compatible with current regex
[root@04baf0b50a63 /]# PS1='[\u@\h \W] \$ '
[root@04baf0b50a63 /] # ls
bin   dev  home  lib64       media  opt   root  sbin  sys  usr
boot  etc  lib   lost+found  mnt    proc  run   srv   tmp  var
```
This removes the requirement of additional characters after the closing bracket, effectively changing it to a requirement that either whitespace or nothing is present between closing bracket and the prompt separator.

### Alternate Designs

The regular expression could be further modified to optionally capture additional characters between the closing bracket and the separator. However, I could not figure out a way to do this that would not also match if the command contained a closing bracket and a valid prompt separator (e.g. if the line looked like `[user@host cwd]$ echo 'hi] $'`).

### Benefits

Improved syntax highlighting on GitHub.

### Possible Drawbacks

There shouldn't be any.

### CODE REVIEW

**Comment by elyscape** [comment]
Pinging @maxbrunsfeld and @50Wliu to make sure this doesn't fall through the cracks.

**Comment by lee-dohm** [comment]
@50Wliu Can you take a look at this?

**Comment by 50Wliu** [comment]
> effectively changing it to a requirement that either whitespace or nothing is present between closing bracket and the prompt separator.

Is there a possibility that prompts may have extra characters between the closing bracket and prompt separator?  Is that what you're referring to in the Alternate Designs section?  If so, could you please share some attempts at solving that problem?  Thanks 🙇‍♂️

**Comment by elyscape** [comment]
>Is there a possibility that prompts may have extra characters between the closing bracket and prompt separator?

Basically, with the patch at present, the following [will be treated as prompts][fixes]:
```shellsession
[root@25f3d5fc32fb /]# echo "'$PS1'"
'[\u@\h \W]\$ '
[root@25f3d5fc32fb /]# PS1='[\u@\h \W] \$ '
[root@25f3d5fc32fb /] # echo "'$PS1'"
'[\u@\h \W] \$ '
```
By contrast, if there is non-whitespace text between the closing bracket and the prompt character, this patch will result in them no longer being treated as prompts. Some examples of things that [would be affected][breaks]:
```shellsession
[root@25f3d5fc32fb /]text# echo "'$PS1'"
'[\u@\h \W]text\$ '
[root@25f3d5fc32fb /]text# PS1='[\u@\h \W] text\$ '
[root@25f3d5fc32fb /] text# echo "'$PS1'"
'[\u@\h \W] text\$ '
[root@25f3d5fc32fb /] text# PS1='[\u@\h \W] text \$ '
[root@25f3d5fc32fb /] text # echo "'$PS1'"
'[\u@\h \W] text \$ '
[root@25f3d5fc32fb /] text # PS1='[\u@\h \W]text \$ '
[root@25f3d5fc32fb /]text # echo "'$PS1'"
'[\u@\h \W]text \$ '
```
As I mentioned in Alternate Designs, I couldn't figure out a good way to allow arbitrary text between the closing bracket and the prompt character without it potentially matching the command itself. You can see this happening already in the examples above where I'm changing `PS1`; notice how those lines are highlighted purple though the backslash escaping the `$` towards the end of the line. I tried various options, but the only way I could find to avoid that was to modify the behavior as described, such that only optional whitespace is allowed between the closing bracket and the prompt character.

All this being said, as far as I'm aware, putting text between the closing bracket and the prompt character isn't a thing that is regularly done. It's more common to put text at the beginning of `PS1`, like what virtualenv does:
```shellsession
[root@b975d6f40c5f ~]# virtualenv venv
New python executable in /root/venv/bin/python2
Also creating executable in /root/venv/bin/python
Installing setuptools, pip, wheel...done.
[root@b975d6f40c5f ~]# source venv/bin/activate
(venv) [root@b975d6f40c5f ~]# echo "'$PS1'"
'(venv) [\u@\h \W]\$ '
(venv) [root@b975d6f40c5f ~]# 
```
This is currently handled but incompletely; the pattern currently assumes that there will be no whitespace between any leading parenthetical and the prompt proper. My proposed change does not alter this. It [could be fixed][venv] fairly trivially, though, by adding `\\s+` to the end of [the group on line 12][group]. Should I do that?

[fixes]: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Felyscape%2Flanguage-shellscript%2F3730dbb284c5fb8fae7b420f15e4a21f8a9e9498%2Fgrammars%2Fshell-session.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Felyscape%2F2290ee1cacf290da99e2ee3da1c8a374%2Fraw%2F2c9714387eb1c48f77893b2771df2a78df42a00e%2Ffixes.sh&code=
[breaks]: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Felyscape%2Flanguage-shellscript%2F3730dbb284c5fb8fae7b420f15e4a21f8a9e9498%2Fgrammars%2Fshell-session.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Felyscape%2F2290ee1cacf290da99e2ee3da1c8a374%2Fraw%2F2c9714387eb1c48f77893b2771df2a78df42a00e%2Fbreaks.sh&code=
[venv]: https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=auto&grammar_url=https%3A%2F%2Fgist.githubusercontent.com%2Felyscape%2F2290ee1cacf290da99e2ee3da1c8a374%2Fraw%2F2c9714387eb1c48f77893b2771df2a78df42a00e%2Fvenv.cson&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Felyscape%2F2290ee1cacf290da99e2ee3da1c8a374%2Fraw%2F2c9714387eb1c48f77893b2771df2a78df42a00e%2Fvenv.sh&code=
[group]: https://github.com/atom/language-shellscript/blob/b0f15084c138256becea931f63f0562c44c515cb/grammars/shell-session.cson#L12

**Comment by 50Wliu** [comment]
@elyscape Thanks for the explanation!  Using that, I came up with the following regex that seems to work in all cases: `\\[\\S+?[@:][^\\n]+?\\].*?`.

[Lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-text&grammar_format=auto&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Felyscape%2Flanguage-shellscript%2F3730dbb284c5fb8fae7b420f15e4a21f8a9e9498%2Fgrammars%2Fshell-session.cson&grammar_text=%27scopeName%27%3A+%27text.shell-session%27%0D%0A%27name%27%3A+%27Shell+Session%27%0D%0A%27fileTypes%27%3A+%5B%0D%0A++%27sh-session%27%0D%0A%5D%0D%0A%27patterns%27%3A+%5B%0D%0A++%7B%0D%0A++++%27match%27%3A+%27%28%3Fx%29%0D%0A++++++%5E%0D%0A++++++%28%3F%3A%0D%0A++++++++%28%0D%0A++++++++++%28%3F%3A%5C%5C%28%5C%5CS%2B%5C%5C%29%29%3F%0D%0A++++++++++%28%3F%3A%0D%0A++++++++++++sh%5C%5CS*%3F+++++++++++++++++++++++%7C%0D%0A++++++++++++%5C%5Cw%2B%5C%5CS%2B%5B%40%3A%5D%5C%5CS%2B%28%3F%3A%5C%5Cs%2B%5C%5CS%2B%29%3F+%7C%0D%0A++++++++++++%5C%5C%5B%5C%5CS%2B%3F%5B%40%3A%5D%5B%5E%5C%5Cn%5D%2B%3F%5C%5C%5D.*%3F%0D%0A++++++++++%29%0D%0A++++++++%29%0D%0A++++++++%5C%5Cs*%0D%0A++++++%29%3F%0D%0A++++++%28%0D%0A++++++++%5B%3E%24%23%25%5D+%7C%0D%0A++++++++%5C%5Cp%7BGreek%7D%0D%0A++++++%29%0D%0A++++++%5C%5Cs%2B%0D%0A++++++%28.*%29%0D%0A++++++%24%0D%0A++++%27%0D%0A++++%27captures%27%3A%0D%0A++++++%271%27%3A%0D%0A++++++++%27name%27%3A+%27entity.other.prompt-prefix.shell-session%27%0D%0A++++++%272%27%3A%0D%0A++++++++%27name%27%3A+%27punctuation.separator.prompt.shell-session%27%0D%0A++++++%273%27%3A%0D%0A++++++++%27name%27%3A+%27source.shell%27%0D%0A++++++++%27patterns%27%3A+%5B%0D%0A++++++++++%27include%27%3A+%27source.shell%27%0D%0A++++++++%5D%0D%0A++%7D%0D%0A++%7B%0D%0A++++%27match%27%3A+%27%5E.%2B%24%27%0D%0A++++%27name%27%3A+%27meta.output.shell-session%27%0D%0A++%7D%0D%0A%5D%0D%0A&code_source=from-text&code_url=https%3A%2F%2Fgist.githubusercontent.com%2Felyscape%2F2290ee1cacf290da99e2ee3da1c8a374%2Fraw%2F2c9714387eb1c48f77893b2771df2a78df42a00e%2Ffixes.sh&code=%5Broot%4025f3d5fc32fb+%2F%5D%23+echo+%22%27%24PS1%27%22%0D%0A%27%5B%5Cu%40%5Ch+%5CW%5D%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5D%23+PS1%3D%27%5B%5Cu%40%5Ch+%5CW%5D+%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5D+%23+echo+%22%27%24PS1%27%22%0D%0A%27%5B%5Cu%40%5Ch+%5CW%5D+%5C%24+%27%0D%0A%0D%0A%5Broot%4025f3d5fc32fb+%2F%5Dtext%23+echo+%22%27%24PS1%27%22%0D%0A%27%5B%5Cu%40%5Ch+%5CW%5Dtext%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5Dtext%23+PS1%3D%27%5B%5Cu%40%5Ch+%5CW%5D+text%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5D+text%23+echo+%22%27%24PS1%27%22%0D%0A%27%5B%5Cu%40%5Ch+%5CW%5D+text%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5D+text%23+PS1%3D%27%5B%5Cu%40%5Ch+%5CW%5D+text+%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5D+text+%23+echo+%22%27%24PS1%27%22%0D%0A%27%5B%5Cu%40%5Ch+%5CW%5D+text+%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5D+text+%23+PS1%3D%27%5B%5Cu%40%5Ch+%5CW%5Dtext+%5C%24+%27%0D%0A%5Broot%4025f3d5fc32fb+%2F%5Dtext+%23+echo+%22%27%24PS1%27%22%0D%0A%27%5B%5Cu%40%5Ch+%5CW%5Dtext+%5C%24+%27)

Example with more contrast:
shell-bracket-prefixes

**Comment by 50Wliu** [comment]
> It could be fixed fairly trivially, though, by adding \\s+ to the end of the group on line 12. Should I do that?

If you could fix this in a separate PR, that would be :sparkles:.

**Comment by elyscape** [comment]
Sounds good! Change pushed. I'll open another PR with the virtualenv fix.

**Pull request merged**
