### PR TITLE
Only match prompts at the start of the line

### PR DESCRIPTION
**Pull request by MakeNowJust**
This behavior cause a problem when we describe cli `--help` output as `console` highlight in `README.md` for example.

    ```console
    $ my-awesome-cli --help
    Usage
      $ my-awesome-cli [--option value]
    
    Options
      --help
      --option value
    
    Example
      $ my-awesome-cli
      $ my-awesome-cli --option value
    ```

Such a Markdown text is highlighted on GitHub with [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark).

highlight example

Not only a real command line but also command output lines starting with `$` was highlighted. It is wrong to read and write shell session.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Thanks - can you please add some specs for this?

**Comment by MakeNowJust** [comment]
Added specs.

@50Wliu, you fixed code block in my pr message to highlight as `sh`, however I explain about `sh-session` (as known as `console`) syntax, sorry. I will revert it.

**Comment by 50Wliu** [comment]
Ah, I thought it was unintentional.  Thanks for clarifying :+1:.

**Comment by 50Wliu** [comment]
Thanks again @MakeNowJust!

**Comment by MakeNowJust** [comment]
Thanks too!

**Pull request merged**
