### PR TITLE
allow spaces between << and the heredoc token

### PR DESCRIPTION
**Pull request by ulidtko**
Hi @lee-dohm, please review

## Before:
screenshot

## After:
screenshot

### CODE REVIEW

**Comment by lee-dohm** [comment]
Please edit the body to include the template and fill in the relevant details. One detail to include is why you only allow space characters instead of whitespace in general?

**Comment by ulidtko** [comment]
Well, primarily because HT, VT, FF, NBSP and all those other whitespace goodies Unicode has to offer are... very weird characters to use middle-line in a shell script. Even the Holy Tab (HT, U+0009) is a dubious choice to delimit a heredoc token.

I actually started with `\s*` at first, but that didn't work for some reason, — and as an afterthought, I figured that the breaking of syntax highlighting is in a sense useful as a pretty good signal that you'd better use a plain U+0020 space here. After all, this is a shell script. Bonus point: the `<<-` form of heredoc makes harsh distinction between tabs and spaces, so one would better be reminded of that.

Sorry about the template, it's pretty boring to fill out. This is a simple, mostly aesthetic change.

**Comment by lee-dohm** [comment]
I understand that the template is boring to fill out, but a little bit of work ahead of time means less back and forth for maintainers. This means that we can respond more quickly to everyone's pull requests.

**Comment by 50Wliu** [comment]
Superseded by #77.  I tested and hard tabs do in fact work.  Thanks for the contributions though @ulidtko!

**Pull request closed without merging**
