### PR TITLE
Fix for…in loop handling

### PR DESCRIPTION
**Pull request by mkhl**
This fixes for…in loop handling by
- updating the grammar to match them more accurately
- adding a (very simple) snippet to insert them

This pull request includes #35, which it would otherwise conflict with.

### CODE REVIEW

**Comment by 50Wliu** [comment]
@mkhl please keep the PRs separate in order to make reviewing easier.  Thanks!

**Comment by mkhl** [comment]
@50Wliu I’m not quite sure how to keep them separate, since they are not independent.

Would it be OK if I closed this one and reopened it once we’re done with #35?

**Comment by 50Wliu** [comment]
@mkhl What I would probably do is include the fixes to the for-in loop in this PR using existing `\\b` regexes, then fix those regexes later in #35.  Alternatively, going the other way would be fine as well.  Your call :).

**Comment by mkhl** [comment]
@50Wliu My intention was to go the other way because I believe #35 to be the more obvious (if larger) change. Your comments indicate that I haven’t done a good job though. :-)

I think holding off on this until after #35 is done would cause the least effort. Whether you’d prefer I close this for that period is your call.

**Pull request closed without merging**
